# Tibor's TLP configuration for ThinkPad P14s.

# Set CPU scaling policies
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

# Disable boost on battery to save power
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

# Set platform profiles
PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=low-power

# Tune down AMD GPU on battery
RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=low
RADEON_POWER_PROFILE_ON_AC=default
RADEON_POWER_PROFILE_ON_BAT=low

# Set battery thresholds
START_CHARGE_THRESH_BAT0=50
STOP_CHARGE_THRESH_BAT0=80
