# Tibor's lazygit configuration.

gui:
  expandFocusedSidePanel: true
  scrollHeight: 15
  showBottomLine: true
  showIcons: true
  theme:
    selectedLineBgColor:
      - black
git:
  allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=format:'%C(blue)%d%Creset %C(yellow)%h%Creset %s, %C(bold green)%an%Creset, %C(green)%cd%Creset'"
