# Tibor's starship configuration.

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[.](bright-black) "

[line_break]
disabled = true

[character]
success_symbol = "[\\$](purple)"
error_symbol = "[\\$](red)"
vicmd_symbol = "[%](purple)"

[directory]
style = "bold blue"

[package]
disabled = true

[battery]

[[battery.display]]
threshold = 20
style = 'bold red'
