# Tibor's tmux dark theme based on Gruvbox dark.

# Pane styles for active vs inactive panes
set-option -g window-style 'fg=#bdae93,bg=#26282b'
set-option -g window-active-style 'fg=#ebdbb2,bg=#1d2021'

# Copy mode and error messages (dark fg works on orange bg)
set-window-option -g mode-style 'fg=#282828,bg=#fe8019'
set-option -g message-style 'fg=#282828,bg=#fe8019'

# Pane indicators in gruvbox dark theme
set-option -g display-panes-active-colour '#ebdbb2'
set-option -g display-panes-colour '#5a524c'

# Pane borders in gruvbox dark theme
set -g pane-border-style fg='#5a524c',bg=default
set -g pane-active-border-style fg='#689d6a',bg=default

# Status bar using gentle gruvbox dark green
set-option -g status-style bg=default,fg='#689d6a'
set-option -g window-status-style fg='#689d6a'
set-option -g window-status-current-style fg='#689d6a',bold
