#!/usr/bin/sh

# Tibor's bspwm configuration.

# Configure monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Configure desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Margins and paddings
bspc config border_width         2
bspc config window_gap           8
bspc config top_padding         16
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       false

# Window split ratio
bspc config split_ratio          0.50

# Window border colouring
bspc config normal_border_color "#282828"
bspc config active_border_color "#282828"
bspc config focused_border_color "#504945"

# Window preselection colouring
bspc config presel_feedback_color "#282828"

# Mouse moving and resising windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Application rules
bspc rule -a Emacs state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
