# Tibor's Kitty light theme using Gruvbox light hard colours with a Flexoki background.

# Set background and foreground colours.
background #fffcf0
foreground #3c3836

# Set cursor colours.
cursor     #000000
cursor_text_color #fffcf0

# Set selection colours.
selection_foreground none
selection_background #d5c4a1

# Set tab bar colours.
tab_bar_background #fffcf0
active_tab_background #fffcf0
inactive_tab_background #fffcf0
active_tab_foreground #689d6a
inactive_tab_foreground #689d6a

# Set the ANSI palette.
color0  #f9f5d7
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #7c6f64
color8  #928374
color9  #9d0006
color10 #79740e
color11 #b57614
color12 #076678
color13 #8f3f71
color14 #427b58
color15 #3c3836
