sensors:
  - tpacpi: /proc/acpi/ibm/thermal
    indices: [0]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0,  46]
  - [1, 43, 56]
  - [2, 50, 61]
  - [3, 56, 66]
  - [4, 60, 69]
  - [5, 65, 71]
  - [6, 68, 73]
  - [7, 70, 79]
  - [127, 75, 32767]
