#!/usr/bin/env bash

# Tibor's herbstluftwm configuration.

# Emit reload hook to all clients
herbstclient emit_hook reload

# Remove all existing keybindings
herbstclient keyunbind --all

# Use Super key as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# Reload WM
herbstclient keybind $Mod-Shift-q reload

# Close windows
herbstclient keybind $Mod-q close

# Application shortcuts
herbstclient keybind $Mod-Return spawn xterm
herbstclient keybind $Mod-Shift-Return spawn emacsclient -nc

# Focus clients
herbstclient keybind $Mod-Left  or , focus left , focus_edge right
herbstclient keybind $Mod-Down  or , focus down , focus_edge up
herbstclient keybind $Mod-Up    or , focus up , focus_edge down
herbstclient keybind $Mod-Right or , focus right , focus_edge left
herbstclient keybind $Mod-h     or , focus left , focus_edge right
herbstclient keybind $Mod-j     or , focus down , focus_edge up
herbstclient keybind $Mod-k     or , focus up , focus_edge down
herbstclient keybind $Mod-l     or , focus right , focus_edge left
herbstclient keybind $Mod-s     or , focus right , focus_edge left

# Move clients
herbstclient keybind $Mod-Shift-Left  shift left
herbstclient keybind $Mod-Shift-Down  shift down
herbstclient keybind $Mod-Shift-Up    shift up
herbstclient keybind $Mod-Shift-Right shift right
herbstclient keybind $Mod-Shift-h     shift left
herbstclient keybind $Mod-Shift-j     shift down
herbstclient keybind $Mod-Shift-k     shift up
herbstclient keybind $Mod-Shift-l     shift right
herbstclient keybind $Mod-Shift-s     shift right

# Create empty frames in desired direction
herbstclient keybind $Mod-u       split   bottom  0.5
herbstclient keybind $Mod-o       split   right   0.5

# Divide frame content into subframes
herbstclient keybind $Mod-Control-space split explode

# Transpose frame layout
herbstclient keybind $Mod-t rotate

# Resize frames
resizestep=0.02
herbstclient keybind $Mod-Control-Left    resize left +$resizestep
herbstclient keybind $Mod-Control-Down    resize down +$resizestep
herbstclient keybind $Mod-Control-Up      resize up +$resizestep
herbstclient keybind $Mod-Control-Right   resize right +$resizestep
herbstclient keybind $Mod-Control-h       resize left +$resizestep
herbstclient keybind $Mod-Control-j       resize down +$resizestep
herbstclient keybind $Mod-Control-k       resize up +$resizestep
herbstclient keybind $Mod-Control-l       resize right +$resizestep
herbstclient keybind $Mod-Control-s       resize right +$resizestep

# Define tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )
herbstclient rename default "${tag_names[0]}" || true

# Select and move between tags
for i in "${!tag_names[@]}" ; do
    herbstclient add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        herbstclient keybind "$Mod-$key" use_index "$i"
        herbstclient keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Cycle through tags
herbstclient keybind $Mod-bracketright use_index +1 --skip-visible
herbstclient keybind $Mod-bracketleft  use_index -1 --skip-visible

# Jump to previous tag
herbstclient keybind $Mod-0 use_previous

# Influence frame client layout
herbstclient keybind $Mod-d remove
#herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toggle
herbstclient keybind $Mod-Shift-f set_attr clients.focus.floating toggle
herbstclient keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
herbstclient keybind $Mod-Shift-m set_attr clients.focus.minimized true
herbstclient keybind $Mod-Control-m jumpto last-minimized
herbstclient keybind $Mod-Shift-p pseudotile toggle

# Cycle through frame client layouts
herbstclient keybind $Mod-space                                                 \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# Configure mouse
herbstclient mouseunbind --all
herbstclient mousebind $Mod-Button1 move
herbstclient mousebind $Mod-Button2 zoom
herbstclient mousebind $Mod-Button3 resize

# Focus clients
herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-n cycle_all
herbstclient keybind $Mod-p cycle_all -1
herbstclient keybind $Mod-i jumpto urgent

# Define theme
herbstclient attr theme.tiling.reset 1
herbstclient attr theme.floating.reset 1
herbstclient set frame_border_active_color '#98971a'
herbstclient set frame_border_normal_color '#3c3836'
herbstclient set frame_bg_active_color '#111313'
herbstclient set frame_bg_normal_color '#111313'
herbstclient set frame_border_width 1
herbstclient set always_show_frame 0
herbstclient set frame_bg_transparent 0
herbstclient set frame_transparent_width 5
herbstclient set frame_gap 4

herbstclient attr theme.title_height 0
herbstclient attr theme.title_font 'Source Code Pro:size=10'
herbstclient attr theme.padding_top 0
herbstclient attr theme.active.color '#3c3836'
herbstclient attr theme.normal.color '#3c3836'
herbstclient attr theme.urgent.color '#3c3836'
herbstclient attr theme.active.title_color '#111313'
herbstclient attr theme.normal.title_color '#928374'
herbstclient attr theme.inner_width 0
herbstclient attr theme.inner_color '#1d2021'
herbstclient attr theme.border_width 1
herbstclient attr theme.floating.border_width 3
herbstclient attr theme.floating.outer_width 1
herbstclient attr theme.floating.outer_color '#3c3836'
herbstclient attr theme.active.inner_color '#98971a'
herbstclient attr theme.urgent.inner_color '#fb4934'
herbstclient attr theme.normal.inner_color '#3c3836'

# Copy inner color to outer color
for state in active urgent normal ; do
    herbstclient substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

herbstclient attr theme.active.outer_width 1
herbstclient attr theme.background_color '#1d2021'

herbstclient set window_gap 4
herbstclient set frame_padding 0
herbstclient set smart_window_surroundings 1
herbstclient set smart_frame_surroundings 1
herbstclient set mouse_recenter_gap 0

# Toggle gaps
herbstclient keybind $Mod-g cycle_value settings.window_gap 0 4 20
herbstclient keybind $Mod-Shift-g cycle_value settings.frame_gap 0 4 20

# Define window rules
herbstclient unrule -F
herbstclient rule focus=on # focus new clients
herbstclient rule floatplacement=smart
herbstclient rule index=e  # open new clients in existing empty frames
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
herbstclient rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herbstclient rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
herbstclient rule class~'(Pinentry|Pinentry-gtk-2)' pseudotile=on

herbstclient set tree_style '╾│ ├└╼─┐'

# X11 laptop hardware keys
herbstclient keybind XF86AudioLowerVolume spawn amixer -q set Master 5%-
herbstclient keybind XF86AudioMicMute spawn amixer -q set Capture toggle
herbstclient keybind XF86AudioMute spawn amixer -q set Master toggle
herbstclient keybind XF86AudioRaiseVolume spawn amixer -q set Master 5%+
herbstclient keybind XF86MonBrightnessDown spawn light -U 5
herbstclient keybind XF86MonBrightnessUp spawn light -A 5

# Rofi
herbstclient keybind $Mod-r spawn rofi -theme gruvbox-dark-hard -show run -font 'Source Code Pro 10'
herbstclient keybind $Mod-w spawn rofi -theme gruvbox-dark-hard -show window -font 'Source Code Pro 10'

# Jump to apps
herbstclient keybind $Mod-b spawn ~/.config/herbstluftwm/jumpto.sh class qutebrowser
herbstclient keybind $Mod-e spawn ~/.config/herbstluftwm/jumpto.sh class emacs
herbstclient keybind $Mod-x spawn ~/.config/herbstluftwm/jumpto.sh class xterm
herbstclient keybind $Mod-v spawn ~/.config/herbstluftwm/jumpto.sh name vterm
herbstclient keybind $Mod-z spawn ~/.config/herbstluftwm/jumpto.sh class zoom

# Maximise
herbstclient keybind $Mod-m spawn /usr/local/share/doc/herbstluftwm/examples/maximize.sh

# Toggle bar
herbstclient keybind $Mod-Shift-b spawn ~/.config/herbstluftwm/togglebar.sh

# Autodetect monitors
herbstclient set auto_detect_monitors true

# Leave room for bar
herbstclient pad 0 24 0 0 0

# Restart bar
pgrep -x polybar && pkill -x polybar
polybar mybar &

# Reset keyboard and trackball settings
x1-k

# Unlock, just to be sure
herbstclient unlock
