# Tibor's gpg-agent configuration on macOS.

# PIN entry program
pinentry-program /opt/homebrew/bin/pinentry-mac

# cache settings
default-cache-ttl 86400
max-cache-ttl 86400

# ssh support
enable-ssh-support
default-cache-ttl-ssh 86400
max-cache-ttl-ssh 86400
